# Generated by Django 5.1.6 on 2025-02-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_transaction_remove_subscription_user_finances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='semester',
        ),
    ]
