# Generated by Django 5.1.6 on 2025-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_loan_user_alter_loan_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
